#! /bin/sh

# AUTOSTART
sxhkd &
sudo illum-d &
picom --no-fading-openclose &
polybarstart &
wmname LG3D &
xsetroot -cursor_name left_ptr &

telegram &
# syncthing -no-browser &

# BSPWM STUFF
bspc monitor -d term mpd browser games V VI VII VIII IX

bspc config border_width			2
bspc config window_gap				4

bspc config split_ratio         	0.50
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config top_padding				25
bspc config focus_follows_pointer	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a firefox desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Surf state=tiled
bspc rule -a Emacs state=tiled desktop='^8'
bspc rule -a Zathura state=tiled
bspc rule -a zoom desktop='^5'
bspc rule -a Telegram desktop='^2'
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a dogecoin-qt desktop='^8'

