#! /bin/sh

#AUTOSTART
sxhkd &
sudo illum-d &
picom &
polybarstart &
feh --bg-fill ~/pix/wallpapers/flcl/206717.jpg &
wmname LG3D &
setxkbmap -option caps:none
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
syncthing -no-browser &
xsetroot -cursor_name left_ptr &

bspc monitor -d term mpd browser games V VI VII VIII

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 25

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Surf state=tiled
bspc rule -a Emacs state=tiled desktop='^8'
bspc rule -a Zathura state=tiled
