#! /bin/sh

#AUTOSTART
sxhkd &
sudo illum-d &
compton &
polybarstart &
feh --bg-scale ~/Pictures/wallpapers/flcl/206717.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a Surf desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Surf state=tiled
bspc rule -a Emacs state=tiled
