#! /bin/sh

export WM=bspwm

setxkbmap -option caps:escape
setxkbmap -layout us,ru,ua -option grp:alt_shift_toggle
setxkbmap -option compose:ralt

# monitor positions
xrandr --output DVI-D-0 --mode 1680x1050 --pos 0x0    --rotate normal \
       --output HDMI-0  --mode 1920x1080 --pos 1680x0 --rotate normal

# AUTOSTART
picom &
wmname LG3D &
xsetroot -cursor_name left_ptr &
polybarstart &
lxpolkit &
sxhkd ~/.config/bspwm/bspwm.sxhkdrc &

# lazywal-cli -r
feh --bg-fill ~/pix/wallpapers/marcus-kistas-we-lost-the-sea-departure-songs.jpg

# syncthing -no-browser &

# BSPWM STUFF
bspc monitor DVI-D-0 -d term mpd browser games V VI VII VIII
bspc monitor HDMI-0 -d tablet1 tablet2
bspc wm --reorder-monitors DVI-D-0 HDMI-0

# for the tablet to only draw on itself
xsetwacom set $(xsetwacom --list devices | grep stylus | sed "s/.*id: //" | sed "s/\t.*//") MapToOutput HEAD-1

bspc config border_width            2
bspc config window_gap              4

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc rule -a Chromium desktop='^3'
bspc rule -a firefox desktop='^3'
bspc rule -a Surf state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a zoom desktop='^5'
bspc rule -a Telegram desktop='^2'
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a discord desktop='^2'
bspc rule -a Tk state=floating
bspc rule -a matplotlib state=floating
bspc rule -a Toplevel state=floating
bspc rule -a com.artyom.game.Main state=floating
bspc rule -a chatterino state=floating

discord&
telegram-desktop&
# jetbrains-toolbox&
