#!/bin/bash
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar def -r &

EX_MONITOR=$(xrandr --query | grep 'VGA-1')
if [[ $EX_MONITOR = *connected* ]]; then
	polybar vga -r &
fi
